### ISSUE TITLE
При генерации подставляется неправильное имя ресурса CMSIS_STARTUP

### ISSUE THREAD

**Issue by asakasinsky** [eugene-babichenko/cubemx2cmake#3]
Доброго дня!

[В этой строке](https://github.com/eugene-babichenko/cubemx2cmake/blob/master/cubemx2cmake/CMakeLists.txt.template#L23) подставляется в имя ресурса значение MCU_LINE и получается:

`file(GLOB_RECURSE CMSIS_STARTUP Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_STM32F103x8.s)`

Такого файла не существует, есть файл:

`file(GLOB_RECURSE CMSIS_STARTUP Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f103xb.s)`

После правки вручную сборка проходит корректно.

**Comment by eugene-babichenko** [comment]
Прикрепите, пожалуйста, проект от CubeMX.

**Comment by asakasinsky** [comment]
[cmake-test.ioc.zip](https://github.com/eugene-babichenko/cubemx2cmake/files/519531/cmake-test.ioc.zip)
